version: '3.8'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - moodle_data:/var/lib/mysql
  moodle:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: db
      MOODLE_DB_PORT: 3306
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: password

volumes:
  moodle_data: